// Prodet catalogue data — names & taglines from the official 2025 catalogue (no prices).
window.PRODET_DATA = {
  sectors: [
    { id: 'hotels', label: 'Hôtels & hébergement' },
    { id: 'restaurants-cafes', label: 'Restaurants & cafés' },
    { id: 'societes-nettoyage', label: 'Sociétés de nettoyage' },
    { id: 'entreprises', label: 'Entreprises' },
    { id: 'revendeurs-grossistes', label: 'Revendeurs & grossistes' },
    { id: 'institutions', label: 'Institutions' },
  ],
  useCases: [
    { id: 'sols', label: 'Nettoyage des sols' },
    { id: 'cuisine-degraissage', label: 'Cuisine & dégraissage' },
    { id: 'sanitaires-desinfection', label: 'Sanitaires & désinfection' },
    { id: 'linge-textiles', label: 'Linge & textiles' },
    { id: 'hygiene-mains', label: 'Hygiène des mains' },
    { id: 'surfaces-vitres', label: 'Surfaces & vitres' },
  ],
  formats: ['1 L', '5 L', '10 L', '20 L', '20 KG'],
  categories: [
    { id: 'restauration-cuisine', label: 'Restauration & cuisine', count: 63 },
    { id: 'buanderie', label: 'Buanderie / blanchisserie', count: 29 },
    { id: 'etage-housekeeping', label: 'Étage / housekeeping', count: 12 },
    { id: 'articles-menagers', label: 'Articles ménagers & hygiène', count: 60 },
  ],
  products: [
    { slug: 'sirafan', name: 'SIRAFAN', tagline: 'Détergent désinfectant toutes surfaces, action antibactérienne, sans rinçage', image: 'sirafan', format: '5 L', useCase: 'sanitaires-desinfection', cat: 'restauration-cuisine', made: true },
    { slug: 'pronet', name: 'PRONET', tagline: 'Nettoyant dégraissant journalier pour sols et murs', format: '20 L', useCase: 'sols', cat: 'restauration-cuisine', made: true },
    { slug: 'pronet-plus', name: 'PRONET PLUS', tagline: 'Nettoyant dégraissant à fond pour sols très sales', format: '20 L', useCase: 'sols', cat: 'restauration-cuisine', made: true },
    { slug: 'prokill', name: 'PROKILL', tagline: 'Nettoyant désinfectant toutes surfaces et matériel', format: '5 L', useCase: 'sanitaires-desinfection', cat: 'restauration-cuisine', made: true },
    { slug: 'profour', name: 'PROFOUR', tagline: 'Dégraissant pour fours, hottes, friteuses et grills', format: '5 L', useCase: 'cuisine-degraissage', cat: 'restauration-cuisine', made: true },
    { slug: 'prolav', name: 'PROLAV', tagline: 'Liquide pour le lavage de la vaisselle en machine', format: '20 L', useCase: 'cuisine-degraissage', cat: 'restauration-cuisine', made: true },
    { slug: 'prorinse', name: 'PRORINSE', tagline: 'Additif de rinçage pour vaisselle en machine', format: '10 L', useCase: 'cuisine-degraissage', cat: 'restauration-cuisine', made: true },
    { slug: 'profon', name: 'PROFON', tagline: 'Nettoyant acide fort pour WC, urinoirs et surfaces dures', format: '20 L', useCase: 'sanitaires-desinfection', cat: 'restauration-cuisine', made: true },
    { slug: 'javel-prodet', name: 'JAVEL PRODET', tagline: 'Désinfectant chloré pour toutes surfaces', format: '5 L', useCase: 'sanitaires-desinfection', cat: 'restauration-cuisine', made: true },
    { slug: 'provitre', name: 'PROVITRE', tagline: 'Nettoyant pour toutes surfaces vitrées', format: '5 L', useCase: 'surfaces-vitres', cat: 'etage-housekeeping', made: true },
    { slug: 'sanihand', name: 'SANIHAND', tagline: 'Savon liquide pour l\u2019hygiène des mains', format: '5 L', useCase: 'hygiene-mains', cat: 'etage-housekeeping', made: true },
    { slug: 'alcogel', name: 'ALCOGEL', tagline: 'Gel hydroalcoolique pour la désinfection des mains', format: '5 L', useCase: 'hygiene-mains', cat: 'etage-housekeeping', made: true },
    { slug: 'progerme', name: 'PROGERME', tagline: 'Nettoyant désodorisant pour toutes surfaces', format: '5 L', useCase: 'sols', cat: 'etage-housekeeping', made: true },
    { slug: 'pilax', name: 'PILAX', tagline: 'Détartrant puissant pour les fonds des WC', format: '750 ml', useCase: 'sanitaires-desinfection', cat: 'etage-housekeeping', made: true },
    { slug: 'prostar', name: 'PROSTAR', tagline: 'Nettoyant désinfectant pour les salles de bains', format: '5 L', useCase: 'sanitaires-desinfection', cat: 'etage-housekeeping', made: true },
    { slug: 'prolax-200', name: 'PROLAX 200', tagline: 'Dégraissant puissant pour les taches difficiles du linge', format: '20 L', useCase: 'linge-textiles', cat: 'buanderie', made: true },
    { slug: 'prolax-500', name: 'PROLAX 500', tagline: 'Produit adoucissant et assouplissant pour le linge', format: '20 L', useCase: 'linge-textiles', cat: 'buanderie', made: true },
    { slug: 'prolax-400', name: 'PROLAX 400', tagline: 'Poudre chlorée pour le blanchiment et la désinfection', format: '10 KG', useCase: 'linge-textiles', cat: 'buanderie', made: true },
    { slug: 'deofresh', name: 'DEOFRESH', tagline: 'Désodorisant d\u2019ambiance (lavande, fleurs)', format: '5 L', useCase: 'surfaces-vitres', cat: 'etage-housekeeping', made: true },
    { slug: 'gant-menage', name: 'Gant de ménage', tagline: 'Accessoire d\u2019hygiène — article commercialisé', format: 'paire', useCase: 'hygiene-mains', cat: 'articles-menagers', made: false },
    { slug: 'lavette-microfibre', name: 'Lavette microfibre', tagline: 'Accessoire de nettoyage — article commercialisé', format: 'pièce', useCase: 'surfaces-vitres', cat: 'articles-menagers', made: false },
    { slug: 'papier-hygienique', name: 'Papier hygiénique 2 plis', tagline: 'Consommable sanitaire — article commercialisé', format: 'sac 60p', useCase: 'sanitaires-desinfection', cat: 'articles-menagers', made: false },
    { slug: 'sac-poubelle', name: 'Sac poubelle géant', tagline: 'Accessoire de nettoyage — article commercialisé', format: 'paquet', useCase: 'sols', cat: 'articles-menagers', made: false },
  ],
};
