/**
 * Académie Prodet — Module 4 confidential range data.
 *
 * ⚠️ SERVER-ONLY. This module holds the Prodet formulas, procedures and
 * material costs (industrial secret). It must NEVER be imported into a client
 * bundle. The runtime guard below throws immediately if that ever happens.
 *
 * Client components receive this data as props ONLY after the academy code has
 * been verified server-side (see `src/app/[locale]/(admin)/admin/academie/gamme`).
 * Client components must import shapes from `./types` with `import type`.
 */

if (typeof window !== 'undefined') {
  throw new Error(
    'academy/range-data is server-only and must not be imported into a client bundle',
  );
}

import type { AcademyFamily, AcademyFamilyKey, AcademyProduct } from './types';

export const ACADEMY_FAMILIES: Record<AcademyFamilyKey, AcademyFamily> = {
  linge: { key: 'linge', fr: 'Linge & lessives', en: 'Laundry', emoji: '👕', col: '#E6EFF8' },
  vaisselle: { key: 'vaisselle', fr: 'Vaisselle', en: 'Dishwash', emoji: '🍽️', col: '#E6F1FB' },
  cuisine: { key: 'cuisine', fr: 'Dégraissage cuisine', en: 'Kitchen degreasing', emoji: '🍳', col: '#FEF3E2' },
  desinfectant: { key: 'desinfectant', fr: 'Désinfectants & sols', en: 'Disinfectants & floors', emoji: '🦠', col: '#E8F5EE' },
  sanitaire: { key: 'sanitaire', fr: 'Sanitaires & détartrants', en: 'Sanitary & descalers', emoji: '🚽', col: '#F3E8F5' },
  mains: { key: 'mains', fr: 'Hygiène des mains', en: 'Hand hygiene', emoji: '🧼', col: '#E8F5EE' },
  special: { key: 'special', fr: 'Spéciaux & autres', en: 'Special & other', emoji: '✨', col: '#EDECEA' },
};

/** Family display order for filter chips. */
export const ACADEMY_FAMILY_ORDER: AcademyFamilyKey[] = [
  'linge',
  'vaisselle',
  'cuisine',
  'desinfectant',
  'sanitaire',
  'mains',
  'special',
];

export const ACADEMY_PRODUCTS: AcademyProduct[] = [
  {
    n: 'Prolax Liquide',
    f: 'linge',
    d_fr: 'Lessive liquide principale pour linge professionnel.',
    d_en: 'Main liquid detergent for professional laundry.',
    cl_fr: 'Hôtels, blanchisseries, restaurants',
    cl_en: 'Hotels, laundries, restaurants',
    lo_fr: 'Tensioactifs (sulfonique + non-ionique) qui lavent, builders (métasilicate, carbonate) pour le pH, EDTA contre le calcaire, CMC anti-redéposition. Version reformulée « buildée ».',
    lo_en: 'Surfactants (sulfonic + non-ionic) that clean, builders (metasilicate, carbonate) for pH, EDTA against limescale, CMC anti-redeposition. Reformulated "built" version.',
    ph: '10–11',
    foam: 'Faible',
    foam_en: 'Low',
    note_fr: 'Reformulation active : ajout EDTA + builders + CMC pour corriger la sous-performance en eau dure.',
    note_en: 'Active reformulation: added EDTA + builders + CMC to fix hard-water underperformance.',
    reform: {
      why: [
        { fr: 'Aucun séquestrant → le calcaire neutralisait les tensioactifs et grisait le linge. Ajout EDTA 3%.', en: 'No sequestrant → limescale neutralized surfactants and greyed laundry. Added EDTA 3%.' },
        { fr: 'Aucun builder alcalin → le pH chutait en lavage. Ajout métasilicate 4% + carbonate 3%.', en: 'No alkaline builder → pH dropped during wash. Added metasilicate 4% + carbonate 3%.' },
        { fr: 'Aucun anti-redéposition → la saleté revenait sur le linge. Ajout CMC 0,8%.', en: 'No anti-redeposition → soil returned onto fabric. Added CMC 0.8%.' },
        { fr: 'Pas de conservateur → risque microbien. Ajout formol 0,15%.', en: 'No preservative → microbial risk. Added formaldehyde 0.15%.' },
      ],
      newF: [
        { ing: 'Eau adoucie', qty: '3 050 g', pct: '61%', role: 'Base' },
        { ing: 'EDTA', qty: '150 g', pct: '3%', role: 'Séquestrant calcaire', changed: true },
        { ing: 'Métasilicate de soude', qty: '200 g', pct: '4%', role: 'Builder alcalin', changed: true },
        { ing: 'Carbonate de soude', qty: '150 g', pct: '3%', role: 'Renfort alcalin', changed: true },
        { ing: 'Acide sulfonique', qty: '325 g', pct: '6,5%', role: 'Tensioactif anionique' },
        { ing: 'Soude liquide', qty: 'q.s.', pct: 'pH 10,5-11', role: 'Neutralise le sulfonique' },
        { ing: 'NANSA PC38', qty: '200 g', pct: '4%', role: 'Tensioactif anionique' },
        { ing: 'NP9 / éthoxylé', qty: '150 g', pct: '3%', role: 'Tensioactif non-ionique' },
        { ing: 'CMC', qty: '40 g', pct: '0,8%', role: 'Anti-redéposition', changed: true },
        { ing: 'Butylglycol', qty: '100 g', pct: '2%', role: 'Solvant gras' },
        { ing: 'Formol', qty: '7 g', pct: '0,15%', role: 'Conservateur', changed: true },
        { ing: 'Eau', qty: 'qsp 5 kg', pct: '—', role: 'Compléter' },
      ],
      newF_en: [
        { ing: 'Softened water', qty: '3 050 g', pct: '61%', role: 'Base' },
        { ing: 'EDTA', qty: '150 g', pct: '3%', role: 'Limescale sequestrant', changed: true },
        { ing: 'Sodium metasilicate', qty: '200 g', pct: '4%', role: 'Alkaline builder', changed: true },
        { ing: 'Sodium carbonate', qty: '150 g', pct: '3%', role: 'Alkaline boost', changed: true },
        { ing: 'Sulfonic acid', qty: '325 g', pct: '6.5%', role: 'Anionic surfactant' },
        { ing: 'Liquid soda', qty: 'q.s.', pct: 'pH 10.5-11', role: 'Neutralizes sulfonic' },
        { ing: 'NANSA PC38', qty: '200 g', pct: '4%', role: 'Anionic surfactant' },
        { ing: 'NP9 / ethoxylate', qty: '150 g', pct: '3%', role: 'Non-ionic surfactant' },
        { ing: 'CMC', qty: '40 g', pct: '0.8%', role: 'Anti-redeposition', changed: true },
        { ing: 'Butylglycol', qty: '100 g', pct: '2%', role: 'Grease solvent' },
        { ing: 'Formaldehyde', qty: '7 g', pct: '0.15%', role: 'Preservative', changed: true },
        { ing: 'Water', qty: 'qsp 5 kg', pct: '—', role: 'Top up' },
      ],
      oldF: [
        { ing: 'Eau adoucie', qty: '3 500 g', pct: '70%', role: 'Base' },
        { ing: 'Acide sulfonique', qty: '400 g', pct: '8%', role: 'Tensioactif principal' },
        { ing: 'Soude liquide', qty: '500 g', pct: '10%', role: 'Neutralise le sulfonique' },
        { ing: 'NANSA PC38', qty: '200 g', pct: '4%', role: 'Tensioactif anionique' },
        { ing: 'NP9', qty: '200 g', pct: '4%', role: 'Tensioactif non-ionique' },
        { ing: 'Butylglycol', qty: '100 g', pct: '2%', role: 'Solvant' },
        { ing: 'Texapon 70', qty: '100 g', pct: '2%', role: 'Tensioactif moussant' },
        { ing: 'Formol', qty: '10 g', pct: '0,2%', role: 'Conservateur' },
      ],
      oldF_en: [
        { ing: 'Softened water', qty: '3 500 g', pct: '70%', role: 'Base' },
        { ing: 'Sulfonic acid', qty: '400 g', pct: '8%', role: 'Main surfactant' },
        { ing: 'Liquid soda', qty: '500 g', pct: '10%', role: 'Neutralizes sulfonic' },
        { ing: 'NANSA PC38', qty: '200 g', pct: '4%', role: 'Anionic surfactant' },
        { ing: 'NP9', qty: '200 g', pct: '4%', role: 'Non-ionic surfactant' },
        { ing: 'Butylglycol', qty: '100 g', pct: '2%', role: 'Solvent' },
        { ing: 'Texapon 70', qty: '100 g', pct: '2%', role: 'Foaming surfactant' },
        { ing: 'Formaldehyde', qty: '10 g', pct: '0.2%', role: 'Preservative' },
      ],
      proc: [
        { fr: "3 050 g d'eau adoucie tiède (~40°C), agitation douce continue.", en: '3 050 g softened water lukewarm (~40°C), gentle continuous stirring.' },
        { fr: "Dissoudre l'EDTA complètement (limpide) — il capture le calcaire en premier.", en: 'Dissolve EDTA fully (clear) — it captures limescale first.' },
        { fr: 'Ajouter métasilicate puis carbonate, dissoudre chacun.', en: 'Add metasilicate then carbonate, dissolve each.' },
        { fr: 'Neutralisation (exothermique, gants+lunettes) : acide sulfonique lentement, puis soude jusqu’à pH 10,5-11.', en: 'Neutralization (exothermic, gloves+goggles): sulfonic acid slowly, then soda to pH 10.5-11.' },
        { fr: 'CMC : saupoudrer très lentement dans le tourbillon, hydrater 10-15 min, zéro grumeau.', en: 'CMC: sprinkle very slowly into vortex, hydrate 10-15 min, no lumps.' },
        { fr: 'Ajouter NANSA puis NP9, agitation douce.', en: 'Add NANSA then NP9, gentle stirring.' },
        { fr: 'Butylglycol, formol. Vérifier pH. Compléter à 5 000 g.', en: 'Butylglycol, formaldehyde. Check pH. Top up to 5 000 g.' },
        { fr: 'Repos 24-48h : pas de séparation, gel ou dépôt.', en: 'Rest 24-48h: no separation, gel or deposit.' },
      ],
      costOld: '7,44',
      costNew: '8,37',
      unitOld: '1,49',
      unitNew: '1,67',
      verdict_fr: "+0,18 DT/kg, mais ce n'est pas un surcoût gaspillé : linge plus doux, anti-grisaillement, meilleure tenue en eau dure. Et moins de sulfonique (325 vs 400 g) → plus son prix monte, plus l'écart se réduit.",
      verdict_en: '+0.18 DT/kg, but not wasted: softer laundry, anti-greying, better hard-water hold. And less sulfonic (325 vs 400 g) → the more its price rises, the smaller the gap.',
    },
  },
  {
    n: 'Prolax Délicat',
    f: 'linge',
    d_fr: 'Lessive douce pour linge couleur et textiles délicats.',
    d_en: 'Mild detergent for colored and delicate textiles.',
    cl_fr: 'Hôtels (linge clients couleur)',
    cl_en: 'Hotels (colored guest laundry)',
    lo_fr: "pH plus neutre que le Prolax standard pour protéger les couleurs et fibres délicates. Pas d'alcalinité forte.",
    lo_en: 'More neutral pH than standard Prolax to protect colors and delicate fibers. No strong alkalinity.',
    ph: '~7–8',
    foam: 'Faible',
    foam_en: 'Low',
  },
  {
    n: 'Prolax Blanc',
    f: 'linge',
    d_fr: 'Lessive poudre pour linge blanc avec anti-redéposition.',
    d_en: 'Powder detergent for white laundry with anti-redeposition.',
    cl_fr: 'Blanchisseries, hôtels',
    cl_en: 'Laundries, hotels',
    lo_fr: "Poudre alcaline avec CMC (anti-redéposition) pour garder le blanc éclatant. Contient déjà du CMC, contrairement à l'ancien Prolax Liquide.",
    lo_en: 'Alkaline powder with CMC (anti-redeposition) to keep whites bright. Already contains CMC, unlike the old Prolax Liquide.',
    ph: '~11',
    foam: 'Faible',
    foam_en: 'Low',
  },
  {
    n: 'Prolax 400',
    f: 'linge',
    d_fr: 'Booster de lavage poudre chloré (détergent renforcé).',
    d_en: 'Chlorinated powder wash booster (reinforced detergent).',
    cl_fr: 'Linge blanc très sale',
    cl_en: 'Heavily soiled white laundry',
    lo_fr: 'Carbonate + métasilicate + STPP + dichloroisocyanurate (source de chlore actif). Blanchiment chloré — blanc uniquement.',
    lo_en: 'Carbonate + metasilicate + STPP + dichloroisocyanurate (active chlorine source). Chlorine bleach — white only.',
    ph: '~11',
    foam: 'Faible',
    foam_en: 'Low',
    note_fr: 'Évolution possible : version oxygénée (percarbonate) pour aller sur le linge couleur.',
    note_en: 'Possible evolution: oxygen version (percarbonate) to work on colored laundry.',
  },
  {
    n: 'Progras',
    f: 'linge',
    d_fr: 'Lessive/dégraissant pour linge très gras.',
    d_en: 'Detergent/degreaser for very greasy laundry.',
    cl_fr: 'Restaurants, cuisines',
    cl_en: 'Restaurants, kitchens',
    lo_fr: 'Renforcé en agents dégraissants pour le linge de cuisine chargé en graisse.',
    lo_en: 'Reinforced with degreasing agents for grease-laden kitchen laundry.',
    ph: 'alcalin',
    foam: 'Faible',
    foam_en: 'Low',
  },
  {
    n: 'Prolax 500',
    f: 'linge',
    d_fr: 'Assouplissant parfumant pour linge.',
    d_en: 'Perfuming fabric softener.',
    cl_fr: 'Hôtels, blanchisseries',
    cl_en: 'Hotels, laundries',
    lo_fr: 'Base cationique (Dequart) qui se fixe sur les fibres pour adoucir. pH acide 4–5 pour la fixation. Parfum pour la persistance.',
    lo_en: 'Cationic base (Dequart) that bonds to fibers to soften. Acidic pH 4–5 for fixation. Fragrance for persistence.',
    ph: '4–5',
    foam: 'Nulle',
    foam_en: 'None',
    note_fr: 'Reformulation active : pH acide + dispersant contre les résidus, taux cationique relevé, parfum encapsulé.',
    note_en: 'Active reformulation: acidic pH + dispersant against residues, raised cationic level, encapsulated fragrance.',
    reform: {
      why: [
        { fr: "Douceur faible (8% base diluée). Monté à 12% d'actif cationique.", en: 'Low softness (8% diluted base). Raised to 12% cationic active.' },
        { fr: 'Pas assez visqueux. Le sel épaissit naturellement un cationique — ajout progressif.', en: 'Not viscous enough. Salt naturally thickens a cationic — added gradually.' },
        { fr: "Parfum non persistant. 2% parfum + parfum encapsulé (libère l'odeur quand on frotte l'éponge).", en: 'Non-lasting scent. 2% fragrance + encapsulated fragrance (releases scent when rubbing the towel).' },
        { fr: 'Résidus par zones. Cause : pH non ajusté + eau dure. Solution : pH acide 4-5 + dispersant (IPA) + eau adoucie.', en: 'Patchy residues. Cause: unadjusted pH + hard water. Fix: acidic pH 4-5 + dispersant (IPA) + softened water.' },
      ],
      newF: [
        { ing: 'Eau adoucie (40-50°C)', qty: '4 050 g', pct: '81%', role: 'Base — adoucie obligatoire', changed: true },
        { ing: 'Base cationique (Dequart)', qty: '600 g', pct: '12%', role: 'Actif douceur (vs 8%)', changed: true },
        { ing: 'Alcool isopropylique', qty: '50 g', pct: '1%', role: 'Dispersant anti-résidus', changed: true },
        { ing: 'Sel (NaCl)', qty: 'q.s.', pct: 'modéré', role: 'Épaississant', changed: true },
        { ing: 'Parfum assoufleur', qty: '100 g', pct: '2%', role: 'Parfum (vs 0,9%)', changed: true },
        { ing: 'Parfum encapsulé', qty: '50 g', pct: '1%', role: 'Persistance longue durée', changed: true },
        { ing: 'Acide citrique', qty: 'q.s.', pct: 'pH 4-5', role: 'Fixe le cationique = anti-résidus', changed: true },
        { ing: 'Conservateur', qty: '5 g', pct: '0,1%', role: 'Anti-microbien' },
        { ing: 'Eau', qty: 'qsp 5 kg', pct: '—', role: 'Compléter' },
      ],
      newF_en: [
        { ing: 'Softened water (40-50°C)', qty: '4 050 g', pct: '81%', role: 'Base — must be softened', changed: true },
        { ing: 'Cationic base (Dequart)', qty: '600 g', pct: '12%', role: 'Softening active (vs 8%)', changed: true },
        { ing: 'Isopropyl alcohol', qty: '50 g', pct: '1%', role: 'Anti-residue dispersant', changed: true },
        { ing: 'Salt (NaCl)', qty: 'q.s.', pct: 'moderate', role: 'Thickener', changed: true },
        { ing: 'Fragrance', qty: '100 g', pct: '2%', role: 'Scent (vs 0.9%)', changed: true },
        { ing: 'Encapsulated fragrance', qty: '50 g', pct: '1%', role: 'Long-lasting', changed: true },
        { ing: 'Citric acid', qty: 'q.s.', pct: 'pH 4-5', role: 'Fixes cationic = anti-residue', changed: true },
        { ing: 'Preservative', qty: '5 g', pct: '0.1%', role: 'Anti-microbial' },
        { ing: 'Water', qty: 'qsp 5 kg', pct: '—', role: 'Top up' },
      ],
      oldF: [
        { ing: 'Eau tiède (50°C)', qty: '4 650 g', pct: '93%', role: 'Base' },
        { ing: 'Base assouplissant', qty: '400 g', pct: '8%', role: 'Actif douceur' },
        { ing: 'Formol', qty: '10 g', pct: '0,2%', role: 'Conservateur' },
        { ing: 'Parfum assoufleur', qty: '45 g', pct: '0,9%', role: 'Parfum' },
      ],
      oldF_en: [
        { ing: 'Lukewarm water (50°C)', qty: '4 650 g', pct: '93%', role: 'Base' },
        { ing: 'Softener base', qty: '400 g', pct: '8%', role: 'Softening active' },
        { ing: 'Formaldehyde', qty: '10 g', pct: '0.2%', role: 'Preservative' },
        { ing: 'Fragrance', qty: '45 g', pct: '0.9%', role: 'Scent' },
      ],
      proc: [
        { fr: 'Eau adoucie 40-50°C, agitation douce et lente (jamais violente).', en: 'Softened water 40-50°C, gentle slow stirring (never vigorous).' },
        { fr: "Base cationique lentement dans l'eau chaude, jusqu'à laiteux homogène.", en: 'Cationic base slowly into warm water, until milky homogeneous.' },
        { fr: 'Étape clé : acide citrique jusqu’à pH 4-5 (réveille et fixe le cationique, anti-résidus).', en: 'Key step: citric acid to pH 4-5 (wakes & fixes the cationic, anti-residue).' },
        { fr: "Sel TRÈS progressivement, la viscosité monte. S'arrêter à la texture voulue (gare au sur-salage).", en: 'Salt VERY gradually, viscosity rises. Stop at desired texture (mind over-salting).' },
        { fr: 'Refroidi (<40°C) : parfum + encapsulé (à froid pour ne pas évaporer).', en: "Cooled (<40°C): fragrance + encapsulated (cold so it doesn't evaporate)." },
        { fr: 'Conservateur, colorant. Compléter à 5 000 g.', en: 'Preservative, colorant. Top up to 5 000 g.' },
        { fr: 'Repos jusqu’à refroidissement. Vérifier viscosité, homogénéité.', en: 'Rest until cooled. Check viscosity, homogeneity.' },
      ],
      costOld: '6,38',
      costNew: '16,39',
      unitOld: '1,28',
      unitNew: '3,28',
      verdict_fr: "Version premium ~3,28 DT/kg (avec encapsulé) ou standard améliorée ~2,38 DT/kg (sans). Reco : deux versions — une standard (douceur+viscosité+anti-résidus à prix maîtrisé) et une premium parfum longue durée plus chère. Le surcoût vient surtout du parfum = valeur perçue.",
      verdict_en: 'Premium ~3.28 DT/kg (with encapsulation) or improved standard ~2.38 DT/kg (without). Rec: two versions — a standard (softness+viscosity+anti-residue at controlled price) and a pricier long-lasting premium. The extra cost is mostly fragrance = perceived value.',
    },
  },
  {
    n: 'Dinol',
    f: 'vaisselle',
    d_fr: 'Liquide vaisselle manuel concentré.',
    d_en: 'Concentrated manual dishwashing liquid.',
    cl_fr: 'Restaurants, cafés',
    cl_en: 'Restaurants, cafés',
    lo_fr: 'Tensioactifs anioniques + amphotères pour la mousse et la douceur peau. Sel pour la viscosité. Excellent rendement (vrac = forte marge).',
    lo_en: 'Anionic + amphoteric surfactants for foam and skin mildness. Salt for viscosity. Excellent yield (bulk = high margin).',
    ph: '~7',
    foam: 'Élevée',
    foam_en: 'High',
  },
  {
    n: 'Solitaire Vaisselle',
    f: 'vaisselle',
    d_fr: 'Liquide vaisselle vert parfumé.',
    d_en: 'Green perfumed dishwashing liquid.',
    cl_fr: 'Cafés, petits restaurants',
    cl_en: 'Cafés, small restaurants',
    lo_fr: 'Système SLES + bétaïne épaissi au sel. Colorant vert + parfum. Mousse abondante (perçue comme efficace).',
    lo_en: 'SLES + betaine system thickened with salt. Green colorant + fragrance. Abundant foam (perceived as effective).',
    ph: '~7',
    foam: 'Élevée',
    foam_en: 'High',
  },
  {
    n: 'Super Clean',
    f: 'vaisselle',
    d_fr: 'Dégraissant vaisselle puissant.',
    d_en: 'Powerful dishwashing degreaser.',
    cl_fr: 'Cuisines professionnelles',
    cl_en: 'Professional kitchens',
    lo_fr: "Plus dégraissant qu'un liquide vaisselle standard, pour la vaisselle très grasse.",
    lo_en: 'More degreasing than a standard dishwashing liquid, for very greasy dishes.',
    ph: '~8',
    foam: 'Moyenne',
    foam_en: 'Medium',
  },
  {
    n: 'Prosav',
    f: 'vaisselle',
    d_fr: 'Détergent vaisselle avec anti-redéposition.',
    d_en: 'Dishwashing detergent with anti-redeposition.',
    cl_fr: 'Restaurants',
    cl_en: 'Restaurants',
    lo_fr: 'Contient du CMC pour éviter la redéposition des graisses sur la vaisselle.',
    lo_en: 'Contains CMC to prevent grease redeposition on dishes.',
    ph: '~8',
    foam: 'Moyenne',
    foam_en: 'Medium',
  },
  {
    n: 'Profour',
    f: 'cuisine',
    d_fr: 'Dégraissant four et surfaces alcalin puissant.',
    d_en: 'Powerful alkaline oven & surface degreaser.',
    cl_fr: 'Cuisines, restaurants',
    cl_en: 'Kitchens, restaurants',
    lo_fr: 'Potasse caustique + métasilicate (saponifient le gras carbonisé) + butylglycol (solvant) + EDTA. Très alcalin — attaque l’aluminium. Booster MEA possible.',
    lo_en: 'Caustic potash + metasilicate (saponify baked grease) + butylglycol (solvent) + EDTA. Very alkaline — attacks aluminium. MEA booster possible.',
    ph: '12–13',
    foam: 'Faible',
    foam_en: 'Low',
  },
  {
    n: 'Prolax 100',
    f: 'cuisine',
    d_fr: 'Agent mouillant/dégraissant concentré.',
    d_en: 'Concentrated wetting/degreasing agent.',
    cl_fr: 'Industrie, cuisines',
    cl_en: 'Industry, kitchens',
    lo_fr: 'Environ 30% de NP9 pur. Très concentré en tensioactif non-ionique. Coût élevé.',
    lo_en: 'About 30% pure NP9. Highly concentrated non-ionic surfactant. High cost.',
    ph: '~8',
    foam: 'Faible',
    foam_en: 'Low',
    note_fr: 'À moderniser : remplacer le NP9 (cher + interdit en Europe) par un alcool gras éthoxylé moins cher et non classé.',
    note_en: 'To modernize: replace NP9 (costly + banned in EU) with a cheaper, unclassified fatty alcohol ethoxylate.',
  },
  {
    n: 'Prolax 200',
    f: 'cuisine',
    d_fr: 'Booster de lavage dégraissant pour linge gras (60°C).',
    d_en: 'Degreasing wash booster for greasy laundry (60°C).',
    cl_fr: 'Buanderies (linge cuisine)',
    cl_en: 'Laundries (kitchen linen)',
    lo_fr: 'Ajouté avec le Prolax Liquide à 60°C pour le gras lourd. Synergie lessive + booster. Solvant + alcali + non-ionique.',
    lo_en: 'Added with Prolax Liquide at 60°C for heavy grease. Detergent + booster synergy. Solvent + alkali + non-ionic.',
    ph: '11–12',
    foam: 'Faible',
    foam_en: 'Low',
    note_fr: 'Reformulation prioritaire : retirer le perchloéthylène (cancérigène) → butylglycol + MEA. Plus sûr et moins cher.',
    note_en: 'Priority reformulation: remove perchloroethylene (carcinogen) → butylglycol + MEA. Safer and cheaper.',
    reform: {
      why: [
        { fr: "Perchloéthylène = cancérigène (CIRC 2A), s'évapore à 60°C → opérateurs exposés. Retiré.", en: 'Perchloroethylene = carcinogen (IARC 2A), evaporates at 60°C → operators exposed. Removed.' },
        { fr: 'Non miscible à l’eau → inutile dans un bain de lavage aqueux. Remplacé par butylglycol (miscible).', en: 'Not water-miscible → useless in an aqueous wash bath. Replaced by butylglycol (miscible).' },
        { fr: 'Coût énorme (7,600/kg dosé à 50%) → produit le plus cher. MEA + métasilicate apportent la puissance.', en: 'Huge cost (7.600/kg at 50%) → most expensive product. MEA + metasilicate provide the power.' },
      ],
      newF: [
        { ing: 'Eau adoucie', qty: '3 150 g', pct: '63%', role: 'Base' },
        { ing: 'EDTA', qty: '100 g', pct: '2%', role: 'Séquestrant', changed: true },
        { ing: 'Métasilicate de soude', qty: '250 g', pct: '5%', role: 'Alcali — saponifie le gras', changed: true },
        { ing: 'Butylglycol', qty: '300 g', pct: '6%', role: 'Solvant (remplace perchlo)', changed: true },
        { ing: 'Alcool éthoxylé / NP9', qty: '250 g', pct: '5%', role: 'Non-ionique dégraissant', changed: true },
        { ing: 'Monoéthanolamine (MEA)', qty: '150 g', pct: '3%', role: 'Booster gras lourd', changed: true },
        { ing: 'Antimousse', qty: '~5 g', pct: 'q.s.', role: 'Faible mousse' },
        { ing: 'Eau', qty: 'qsp 5 kg', pct: '—', role: 'Compléter' },
      ],
      newF_en: [
        { ing: 'Softened water', qty: '3 150 g', pct: '63%', role: 'Base' },
        { ing: 'EDTA', qty: '100 g', pct: '2%', role: 'Sequestrant', changed: true },
        { ing: 'Sodium metasilicate', qty: '250 g', pct: '5%', role: 'Alkali — saponifies grease', changed: true },
        { ing: 'Butylglycol', qty: '300 g', pct: '6%', role: 'Solvent (replaces perchlo)', changed: true },
        { ing: 'Ethoxylate / NP9', qty: '250 g', pct: '5%', role: 'Non-ionic degreaser', changed: true },
        { ing: 'Monoethanolamine (MEA)', qty: '150 g', pct: '3%', role: 'Heavy-grease booster', changed: true },
        { ing: 'Antifoam', qty: '~5 g', pct: 'q.s.', role: 'Low foam' },
        { ing: 'Water', qty: 'qsp 5 kg', pct: '—', role: 'Top up' },
      ],
      oldF: [
        { ing: 'NP9', qty: '1 000 g', pct: '20%', role: 'Tensioactif non-ionique' },
        { ing: 'Butylglycol', qty: '500 g', pct: '10%', role: 'Solvant' },
        { ing: 'Perchloéthylène', qty: '2 500 g', pct: '50%', role: 'Solvant chloré (RETIRÉ)' },
        { ing: 'Eau adoucie', qty: '1 000 g', pct: '20%', role: 'Base' },
      ],
      oldF_en: [
        { ing: 'NP9', qty: '1 000 g', pct: '20%', role: 'Non-ionic surfactant' },
        { ing: 'Butylglycol', qty: '500 g', pct: '10%', role: 'Solvent' },
        { ing: 'Perchloroethylene', qty: '2 500 g', pct: '50%', role: 'Chlorinated solvent (REMOVED)' },
        { ing: 'Softened water', qty: '1 000 g', pct: '20%', role: 'Base' },
      ],
      proc: [
        { fr: 'Eau adoucie (~3 150 g), chauffer ~40°C, agitation douce.', en: 'Softened water (~3 150 g), heat ~40°C, gentle stirring.' },
        { fr: 'EDTA, dissoudre jusqu’à limpidité.', en: 'EDTA, dissolve until clear.' },
        { fr: 'Métasilicate progressivement, dissoudre. Solution alcaline.', en: 'Metasilicate gradually, dissolve. Alkaline solution.' },
        { fr: 'MEA lentement (gants+lunettes, alcalin).', en: 'MEA slowly (gloves+goggles, alkaline).' },
        { fr: 'Butylglycol, mélanger. Puis alcool éthoxylé doucement.', en: 'Butylglycol, mix. Then ethoxylate gently.' },
        { fr: 'Antimousse si besoin. Compléter à 5 000 g.', en: 'Antifoam if needed. Top up to 5 000 g.' },
        { fr: 'Repos 24-48h. Test linge gras 60°C/15min avec Prolax Liquide.', en: 'Rest 24-48h. Greasy-laundry test 60°C/15min with Prolax Liquide.' },
      ],
      costOld: '30,55',
      costNew: '6,86',
      unitOld: '6,11',
      unitNew: '1,37',
      verdict_fr: 'Gain spectaculaire : −78% de coût matières (1,37 vs 6,11 DT/kg) en retirant le perchlo cher et dosé à 50%. Plus sûr ET beaucoup moins cher — la reformulation la plus rentable de la gamme.',
      verdict_en: 'Spectacular gain: −78% material cost (1.37 vs 6.11 DT/kg) by removing the costly perchlo dosed at 50%. Safer AND far cheaper — the most profitable reformulation in the range.',
    },
  },
  {
    n: 'Sirafan',
    f: 'desinfectant',
    d_fr: 'Détergent désinfectant désodorisant toutes surfaces, sans javel.',
    d_en: 'Detergent disinfectant deodorizer for all surfaces, bleach-free.',
    cl_fr: 'Hôtels, restaurants, collectivités',
    cl_en: 'Hotels, restaurants, institutions',
    lo_fr: "Tensioactifs + agent désinfectant (ammonium quaternaire) + parfum. Prêt à l'emploi, sans rinçage, action antibactérienne. Biodégradabilité >90%.",
    lo_en: 'Surfactants + disinfecting agent (quaternary ammonium) + fragrance. Ready-to-use, no rinse, antibacterial action. Biodegradability >90%.',
    ph: '~7',
    foam: 'Faible',
    foam_en: 'Low',
  },
  {
    n: 'Sani Pro',
    f: 'desinfectant',
    d_fr: 'Désinfectant professionnel sols et surfaces.',
    d_en: 'Professional floor & surface disinfectant.',
    cl_fr: 'Collectivités, santé',
    cl_en: 'Institutions, healthcare',
    lo_fr: 'Ammonium quaternaire pour la désinfection + tensioactifs pour le nettoyage.',
    lo_en: 'Quaternary ammonium for disinfection + surfactants for cleaning.',
    ph: '~8',
    foam: 'Faible',
    foam_en: 'Low',
  },
  {
    n: 'Manocid',
    f: 'desinfectant',
    d_fr: 'Désinfectant concentré.',
    d_en: 'Concentrated disinfectant.',
    cl_fr: 'Collectivités',
    cl_en: 'Institutions',
    lo_fr: 'Agent biocide concentré. Conservateur dans la formule.',
    lo_en: 'Concentrated biocidal agent. Preservative in the formula.',
    ph: '~7',
    foam: 'Faible',
    foam_en: 'Low',
  },
  {
    n: 'Prokill',
    f: 'desinfectant',
    d_fr: 'Désinfectant détergent sols.',
    d_en: 'Floor disinfectant detergent.',
    cl_fr: 'Hôtels, restaurants',
    cl_en: 'Hotels, restaurants',
    lo_fr: 'Nettoie et désinfecte les sols en une étape. Parfumé.',
    lo_en: 'Cleans and disinfects floors in one step. Perfumed.',
    ph: '~8',
    foam: 'Faible',
    foam_en: 'Low',
  },
  {
    n: 'Gresil',
    f: 'desinfectant',
    d_fr: 'Désinfectant parfumé type crésyl.',
    d_en: 'Cresyl-type perfumed disinfectant.',
    cl_fr: 'Sols, espaces communs',
    cl_en: 'Floors, common areas',
    lo_fr: 'Désinfectant à odeur caractéristique pour sols et surfaces. Effet désodorisant fort.',
    lo_en: 'Disinfectant with characteristic odor for floors and surfaces. Strong deodorizing effect.',
    ph: '~8',
    foam: 'Faible',
    foam_en: 'Low',
  },
  {
    n: 'Prolac',
    f: 'sanitaire',
    d_fr: 'Détartrant doux sanitaires.',
    d_en: 'Mild sanitary descaler.',
    cl_fr: 'Hôtels, sanitaires',
    cl_en: 'Hotels, restrooms',
    lo_fr: 'Acide doux (citrique/phosphorique) pour dissoudre le calcaire sans agresser les surfaces. Détartrage régulier.',
    lo_en: 'Mild acid (citric/phosphoric) to dissolve limescale without harming surfaces. Regular descaling.',
    ph: '2–4',
    foam: 'Faible',
    foam_en: 'Low',
  },
  {
    n: 'Profon',
    f: 'sanitaire',
    d_fr: "Détartrant fort à l'acide chlorhydrique.",
    d_en: 'Strong hydrochloric acid descaler.',
    cl_fr: 'Sanitaires très entartrés',
    cl_en: 'Heavily scaled restrooms',
    lo_fr: 'Acide chlorhydrique concentré (~499kg/lot). Détartrage puissant. Corrosif — manipulation prudente.',
    lo_en: 'Concentrated hydrochloric acid (~499kg/batch). Powerful descaling. Corrosive — handle carefully.',
    ph: '~1',
    foam: 'Faible',
    foam_en: 'Low',
  },
  {
    n: 'Pilax',
    f: 'sanitaire',
    d_fr: 'Gel WC détartrant épaissi.',
    d_en: 'Thickened WC descaling gel.',
    cl_fr: 'Sanitaires',
    cl_en: 'Restrooms',
    lo_fr: 'Acide + Dacamid (amide, épaississant) pour que le gel accroche sous la lunette. Détartre et désinfecte les WC.',
    lo_en: 'Acid + Dacamid (amide, thickener) so the gel clings under the rim. Descales and disinfects toilets.',
    ph: '~1–2',
    foam: 'Faible',
    foam_en: 'Low',
  },
  {
    n: 'Prorinse',
    f: 'sanitaire',
    d_fr: 'Liquide de rinçage acide (séchage rapide).',
    d_en: 'Acidic rinse aid (fast drying).',
    cl_fr: 'Lave-vaisselle pro',
    cl_en: 'Pro dishwashers',
    lo_fr: 'Acide citrique + tensioactif faible mousse pour éviter les traces de calcaire et accélérer le séchage.',
    lo_en: 'Citric acid + low-foam surfactant to avoid limescale spots and speed drying.',
    ph: '~3',
    foam: 'Très faible',
    foam_en: 'Very low',
  },
  {
    n: 'Prostar',
    f: 'sanitaire',
    d_fr: 'Détartrant/rénovateur surfaces.',
    d_en: 'Surface descaler/renovator.',
    cl_fr: 'Sanitaires, cuisines',
    cl_en: 'Restrooms, kitchens',
    lo_fr: 'Acide pour éliminer tartre et dépôts minéraux, redonner de la brillance.',
    lo_en: 'Acid to remove scale and mineral deposits, restore shine.',
    ph: '~2',
    foam: 'Faible',
    foam_en: 'Low',
  },
  {
    n: 'Sanihand',
    f: 'mains',
    d_fr: 'Savon liquide mains.',
    d_en: 'Liquid hand soap.',
    cl_fr: 'Hôtels, restaurants, bureaux',
    cl_en: 'Hotels, restaurants, offices',
    lo_fr: 'SLES + bétaïne (douceur peau) épaissi au sel, glycérine hydratante, parfum. pH proche du neutre.',
    lo_en: 'SLES + betaine (skin mildness) thickened with salt, moisturizing glycerin, fragrance. Near-neutral pH.',
    ph: '~6',
    foam: 'Élevée',
    foam_en: 'High',
  },
  {
    n: 'Alcohand',
    f: 'mains',
    d_fr: 'Gel/solution hydroalcoolique mains.',
    d_en: 'Hydroalcoholic hand gel/solution.',
    cl_fr: 'Collectivités, santé, accueil',
    cl_en: 'Institutions, healthcare, reception',
    lo_fr: 'Alcool (éthanol/IPA) à concentration désinfectante + agent hydratant. Désinfection sans rinçage.',
    lo_en: 'Alcohol (ethanol/IPA) at disinfecting concentration + moisturizer. No-rinse disinfection.',
    ph: '~6',
    foam: 'Nulle',
    foam_en: 'None',
  },
  {
    n: 'Alcogel',
    f: 'mains',
    d_fr: 'Gel hydroalcoolique épaissi.',
    d_en: 'Thickened hydroalcoholic gel.',
    cl_fr: 'Accueil, bureaux',
    cl_en: 'Reception, offices',
    lo_fr: 'Alcool + Carbomer (épaississant gel) pour une texture gel agréable. Désinfection des mains.',
    lo_en: 'Alcohol + Carbomer (gel thickener) for a pleasant gel texture. Hand disinfection.',
    ph: '~6',
    foam: 'Nulle',
    foam_en: 'None',
  },
  {
    n: 'Provitre',
    f: 'special',
    d_fr: 'Nettoyant vitres et surfaces brillantes.',
    d_en: 'Glass & shiny surface cleaner.',
    cl_fr: 'Hôtels, bureaux, vitrines',
    cl_en: 'Hotels, offices, storefronts',
    lo_fr: 'Alcool/solvant + tensioactif faible + ammoniac léger pour un séchage rapide sans traces.',
    lo_en: 'Alcohol/solvent + low surfactant + light ammonia for fast streak-free drying.',
    ph: '~8',
    foam: 'Nulle',
    foam_en: 'None',
  },
  {
    n: 'Clorax',
    f: 'special',
    d_fr: 'Eau de javel (hypochlorite).',
    d_en: 'Bleach (hypochlorite).',
    cl_fr: 'Tous secteurs',
    cl_en: 'All sectors',
    lo_fr: 'Hypochlorite de sodium stabilisé. Désinfection et blanchiment. Ne jamais mélanger avec un acide.',
    lo_en: 'Stabilized sodium hypochlorite. Disinfection and bleaching. Never mix with acid.',
    ph: '~12',
    foam: 'Nulle',
    foam_en: 'None',
  },
  {
    n: 'Pronet',
    f: 'special',
    d_fr: 'Nettoyant désinfectant sol chloré (soude + javel).',
    d_en: 'Chlorinated floor disinfectant cleaner (soda + bleach).',
    cl_fr: 'Sols industriels',
    cl_en: 'Industrial floors',
    lo_fr: "Soude + javel (refroidir <30°C avant d'ajouter la javel). Nettoyage dégraissant + désinfection chlorée puissante.",
    lo_en: 'Soda + bleach (cool <30°C before adding bleach). Degreasing cleaning + powerful chlorine disinfection.',
    ph: '~13',
    foam: 'Faible',
    foam_en: 'Low',
  },
  {
    n: 'Anti-algues piscine',
    f: 'special',
    d_fr: 'Traitement anti-algues pour piscines.',
    d_en: 'Anti-algae pool treatment.',
    cl_fr: 'Hôtels avec piscine',
    cl_en: 'Hotels with pools',
    lo_fr: "Agent algicide (ammonium quaternaire) pour prévenir et traiter les algues dans l'eau de piscine.",
    lo_en: 'Algicide agent (quaternary ammonium) to prevent and treat algae in pool water.',
    ph: '~7',
    foam: 'Faible',
    foam_en: 'Low',
  },
  {
    n: 'Deofresh',
    f: 'special',
    d_fr: "Parfum d'ambiance / désodorisant concentré.",
    d_en: 'Air freshener / concentrated deodorizer.',
    cl_fr: 'Hôtels, espaces communs',
    cl_en: 'Hotels, common areas',
    lo_fr: "Parfum + émulgateur + fixateur dans l'eau. Le ratio émulgateur/parfum doit être suffisant pour rester limpide et stable.",
    lo_en: 'Fragrance + emulsifier + fixative in water. The emulsifier/fragrance ratio must be high enough to stay clear and stable.',
    ph: '~7',
    foam: 'Nulle',
    foam_en: 'None',
    note_fr: 'Reformulation active : ratio émulgateur relevé (anti-séparation) + eau adoucie + conservateur ajouté.',
    note_en: 'Active reformulation: raised emulsifier ratio (anti-separation) + softened water + added preservative.',
    reform: {
      why: [
        { fr: 'Séparation du parfum. Cause : ratio émulgateur/parfum trop faible (0,44:1). Monté à 1,2:1.', en: 'Fragrance separation. Cause: emulsifier/fragrance ratio too low (0.44:1). Raised to 1.2:1.' },
        { fr: 'Eau STEG (calcaire) déstabilisait l’émulsion. Remplacée par eau adoucie.', en: 'STEG water (limescale) destabilized the emulsion. Replaced with softened water.' },
        { fr: 'Aucun conservateur → risque microbien. Ajout formol 0,1%.', en: 'No preservative → microbial risk. Added formaldehyde 0.1%.' },
      ],
      newF: [
        { ing: 'Eau adoucie (35°C)', qty: '4 250 g', pct: '85%', role: 'Base — adoucie', changed: true },
        { ing: 'Parfum assoufleur', qty: '250 g', pct: '5%', role: 'Parfum' },
        { ing: 'Émulgateur (Sabowax)', qty: '300 g', pct: '6%', role: 'Solubilisant — ratio relevé', changed: true },
        { ing: 'Alcool fixateur', qty: '150 g', pct: '3%', role: 'Fixe le parfum' },
        { ing: 'Conservateur (formol)', qty: '5 g', pct: '0,1%', role: 'Anti-microbien', changed: true },
        { ing: 'Colorant', qty: 'q.s.', pct: '—', role: 'Esthétique' },
      ],
      newF_en: [
        { ing: 'Softened water (35°C)', qty: '4 250 g', pct: '85%', role: 'Base — softened', changed: true },
        { ing: 'Fragrance', qty: '250 g', pct: '5%', role: 'Scent' },
        { ing: 'Emulsifier (Sabowax)', qty: '300 g', pct: '6%', role: 'Solubilizer — raised ratio', changed: true },
        { ing: 'Fixative alcohol', qty: '150 g', pct: '3%', role: 'Fixes the scent' },
        { ing: 'Preservative', qty: '5 g', pct: '0.1%', role: 'Anti-microbial', changed: true },
        { ing: 'Colorant', qty: 'q.s.', pct: '—', role: 'Aesthetics' },
      ],
      oldF: [
        { ing: 'Parfum assoufleur', qty: '~340 g', pct: '4,5kg/65L', role: 'Parfum' },
        { ing: 'Émulgateur (Sabowax)', qty: '~150 g', pct: '2kg/65L', role: 'Solubilisant (insuffisant)' },
        { ing: 'Alcool fixateur', qty: '~150 g', pct: '2L/65L', role: 'Fixateur' },
        { ing: 'Eau STEG', qty: '~65 L', pct: '—', role: 'Base (calcaire)' },
      ],
      oldF_en: [
        { ing: 'Fragrance', qty: '~340 g', pct: '4.5kg/65L', role: 'Scent' },
        { ing: 'Emulsifier (Sabowax)', qty: '~150 g', pct: '2kg/65L', role: 'Solubilizer (insufficient)' },
        { ing: 'Fixative alcohol', qty: '~150 g', pct: '2L/65L', role: 'Fixative' },
        { ing: 'STEG water', qty: '~65 L', pct: '—', role: 'Base (limescale)' },
      ],
      proc: [
        { fr: 'Phase huileuse (à part) : mélanger parfum + émulgateur + fixateur jusqu’à limpide.', en: 'Oily phase (separate): mix fragrance + emulsifier + fixative until clear.' },
        { fr: 'Eau adoucie tiède (~35°C) dans le récipient, agitation douce.', en: 'Lukewarm softened water (~35°C) in vessel, gentle stirring.' },
        { fr: 'Verser la phase huileuse TRÈS lentement en filet dans l’eau. Solution limpide.', en: 'Pour oily phase VERY slowly as a stream into water. Clear solution.' },
        { fr: 'Conservateur, colorant. Compléter à 5 000 g.', en: 'Preservative, colorant. Top up to 5 000 g.' },
        { fr: 'Observer plusieurs jours : limpide et stable = réparé. Sinon augmenter l’émulgateur.', en: 'Observe several days: clear and stable = fixed. Else increase emulsifier.' },
      ],
      costOld: '',
      costNew: '',
      unitOld: '3,33',
      unitNew: '3,40',
      verdict_fr: 'Coût quasi identique (~3,40 vs 3,33 DT/kg) — la correction est presque gratuite. Si la séparation persiste malgré le ratio relevé, passer à un solubilisant PEG-40 huile de ricin (Cremophor RH40), garanti limpide et stable.',
      verdict_en: 'Almost identical cost (~3.40 vs 3.33 DT/kg) — the fix is nearly free. If separation persists despite the raised ratio, switch to a PEG-40 castor oil solubilizer (Cremophor RH40), guaranteed clear and stable.',
    },
  },
];
